
type ProjectOrientation = "landscape" | "portrait" | "auto"

declare interface ProjectDesc {
	id: string;
	title: string;
	icon: string;
	mainScene: string;
	/** Path to project`s folder. Filed generated by fs */
	dir: string;
	defaultFont: string;
	screenOrientation: ProjectOrientation;
	width: number;
	height: number;
	portraitWidth: number;
	portraitHeight: number;
	renderResolution: number;
	renderResolutionMobile: number;
	framesSkipLimit: number;
	dynamicStageSize: boolean;
	preventUpscale: boolean;
	webfontloader: {
		custom?: {
			families: string[]
		};
		google?: {
			families: string[]
		};
		timeout: number
	} | null,
	fontHolderText: string,
	mipmap: false,
	version: string,
	soundFormats: string[],
	soundDefaultBitrate: number,
	soundBitrates: {
	},
	loadOnDemandSounds: {
	},
	loadOnDemandTextures: {
	},
	__loadOnDemandTexturesFolders: {

	},
	defaultMusVol: number,
	defaultSoundsVol: number,
	embedLocales: true,
	__localesNewKeysPrefix: string,
	__suspendWarnings: number[],
	__externalTranslations: string[],
	autoFullscreenDesktop: false,
	autoFullscreenMobile: false,
	__proxyFetchesViaNodeServer: false,
	__group: string,
	__webpack: {
		debug: string,
		production: string
	},
	libs: string[],
}

export type { ProjectDesc, ProjectOrientation };
